### ISSUE TITLE
Extracting and opening files

### ISSUE THREAD

**Issue by ghost** [SCell555/7zip-vpk#1]
**Extracting:**
When extracting files, barely any get extracted, only top folder and top file

**Opening files:** - _(This wouldn't be as important if extracting worked)_
Opening any files in 7-zip from .vpk crash 7-zip

**Comment by SCell555** [comment]
I'm not able to produce any crashes in clean VM on x86/x64 versions. Please provide steps to reproduce said issue.

**Comment by ghost** [comment]
1. Issue:
- Extract any .vpk
- Only some files get extracted

2. Issue:
- Open a .vpk file with 7-zip
- Open or move any file from the .vpk
- 7-zip crashes before opening/moving the file

**Comment by SCell555** [comment]
Can you check if crash was fixed in https://github.com/SCell555/7zip-vpk/releases/tag/v2.1?

**Comment by ghost** [comment]
Updated the codecs with 2.1 and for some reason 7-zip doesn't crash when opening or moving files from the .vpk in the game location but when moving the .vpk to a different folder then opening it and moving files from the moved .vpk it crashes

**Comment by SCell555** [comment]
Handler now will refuse to load vpk if any of content vpks are missing.
