### ISSUE TITLE
Can you compile a "dir" .vpk?

### ISSUE THREAD

**Issue by ghost** [SCell555/7zip-vpk#2]
I'm currently working with the CS:GO game files and I replaced some sounds, is there a way to compile it as it is in the game folder?
Basically about 150 pak01_XXX.vpk's (each ~100mb) and a pak01_dir.vpk (12mb)
Or would a single "pak01_dir.vpk" (17gb) with all the files work?

**Comment by SCell555** [comment]
No. Without making changes to 7-Zip itself, it isn't possible for this library to create multi-vpk paks. Also safe vpk size is < 2GB.
