### ISSUE TITLE
Compression level not greyed out

### ISSUE THREAD

**Issue by SirYodaJedi** [SCell555/7zip-vpk#3]
I noticed when trying this out on 7-Zip 22.01 (Win64) that the `Compression level` option is selectable, but does nothing. Since VPKs cannot be compressed (unfortunately), this option should be greyed out to avoid confusion.

![image](https://github.com/SCell555/7zip-vpk/assets/50331474/8b341e6e-9c50-4a47-aae4-c500e9446cee)

**Comment by SCell555** [comment]
This is not possible to tell 7-Zip that a format plugin does not support compression levels. This only works in my [custom 7-Zip](https://github.com/SCell555/7-Zip-zstd), where I made a custom extension for this plugin.
